In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers import Conv2D, MaxPooling2D, Flatten
from keras.optimizers import SGD, Adam
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import model_from_json
import os

Using TensorFlow backend.
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [4]:
y_train = np.load('./data_for_prediction/y_train.npy')
x_train = np.load('./data_for_prediction/x_train.npy')

# evaluating model

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x_train, (y_train>=15.0).astype(int), test_size=0.25, random_state=42)


In [3]:
model = Sequential([
    Dense(40, input_dim=10),  
    Activation('softmax'),
    Dense(units=20,activation='softmax'),
    Dense(1),
    Activation('sigmoid'),
])

In [4]:
model.compile(optimizer="rmsprop",
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [7]:
model.fit(X_train, Y_train, epochs=10, batch_size=1000)

Epoch 1/10
3114517/3114517 [==============================] - 13s 4us/step - loss: 0.3820 - acc: 0.8381
Epoch 2/10
3114517/3114517 [==============================] - 15s 5us/step - loss: 0.2027 - acc: 0.9269
Epoch 3/10
3114517/3114517 [==============================] - 12s 4us/step - loss: 0.1939 - acc: 0.9284
Epoch 4/10
3114517/3114517 [==============================] - 13s 4us/step - loss: 0.1914 - acc: 0.9289
Epoch 5/10
3114517/3114517 [==============================] - 12s 4us/step - loss: 0.1909 - acc: 0.9290
Epoch 6/10
3114517/3114517 [==============================] - 13s 4us/step - loss: 0.1903 - acc: 0.9292
Epoch 7/10
3114517/3114517 [==============================] - 16s 5us/step - loss: 0.1899 - acc: 0.9293
Epoch 8/10
3114517/3114517 [==============================] - 12s 4us/step - loss: 0.1894 - acc: 0.9295
Epoch 9/10
3114517/3114517 [==============================] - 12s 4us/step - loss: 0.1890 - acc: 0.9296
Epoch 10/10
3114517/3114517 [==============================] - 1

In [9]:
loss, accuracy = model.evaluate(X_test, Y_test)

1038173/1038173 [==============================] - 26s 25us/step


In [10]:
print('loss: ', loss)
print('accuracy', accuracy)

loss:  0.187252264973
accuracy 0.930857381187


In [11]:
model.predict(X_test)

array([[ 0.00578272],
       [ 0.96424693],
       [ 0.00623321],
       ..., 
       [ 0.15346076],
       [ 0.0040099 ],
       [ 0.0072506 ]], dtype=float32)

# building model and predict

In [7]:
model = Sequential([
    Dense(40, input_dim=10),  
    Activation('softmax'),
    Dense(units=20,activation='softmax'),
    Dense(1),
    Activation('sigmoid'),
])
model.compile(optimizer="rmsprop",
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, (y_train>=15.0).astype(int), epochs=10, batch_size=1000)

Epoch 1/10
4152690/4152690 [==============================] - 21s 5us/step - loss: 0.5676 - acc: 0.7447
Epoch 2/10
4152690/4152690 [==============================] - 21s 5us/step - loss: 0.5606 - acc: 0.7516
Epoch 3/10
4152690/4152690 [==============================] - 18s 4us/step - loss: 0.5606 - acc: 0.7516
Epoch 4/10
4152690/4152690 [==============================] - 19s 5us/step - loss: 0.5606 - acc: 0.7516
Epoch 5/10
4152690/4152690 [==============================] - 18s 4us/step - loss: 0.5606 - acc: 0.7516
Epoch 6/10
4152690/4152690 [==============================] - 17s 4us/step - loss: 0.5606 - acc: 0.7516
Epoch 7/10
4152690/4152690 [==============================] - 17s 4us/step - loss: 0.5606 - acc: 0.7516
Epoch 8/10
4152690/4152690 [==============================] - 17s 4us/step - loss: 0.5606 - acc: 0.7516
Epoch 9/10
4152690/4152690 [==============================] - 19s 5us/step - loss: 0.5606 - acc: 0.7516
Epoch 10/10
4152690/4152690 [==============================] - 1

In [54]:
def build_model(x_train, y_train):
    

    model = Sequential([
    Dense(40, input_dim=10),  
    Activation('softmax'),
    Dense(units=20,activation='softmax'),
    Dense(1),
    Activation('sigmoid'),
])
    model.compile(optimizer="rmsprop",
              loss='binary_crossentropy',
              metrics=['accuracy'])
    model.fit(x_train, (y_train>=15.0).astype(int), epochs=10, batch_size=1000)
    return model

In [57]:
model = build_model(x_train, y_train)

Epoch 1/10
4152690/4152690 [==============================] - 23s 6us/step - loss: 0.3383 - acc: 0.8604
Epoch 2/10
4152690/4152690 [==============================] - 19s 5us/step - loss: 0.1956 - acc: 0.9284
Epoch 3/10
4152690/4152690 [==============================] - 20s 5us/step - loss: 0.1923 - acc: 0.9288
Epoch 4/10
4152690/4152690 [==============================] - 18s 4us/step - loss: 0.1909 - acc: 0.9290
Epoch 5/10
4152690/4152690 [==============================] - 18s 4us/step - loss: 0.1896 - acc: 0.9293
Epoch 6/10
4152690/4152690 [==============================] - 19s 5us/step - loss: 0.1878 - acc: 0.9295
Epoch 7/10
4152690/4152690 [==============================] - 20s 5us/step - loss: 0.1862 - acc: 0.9298
Epoch 8/10
4152690/4152690 [==============================] - 19s 4us/step - loss: 0.1854 - acc: 0.9300
Epoch 9/10
4152690/4152690 [==============================] - 18s 4us/step - loss: 0.1850 - acc: 0.9302
Epoch 10/10
4152690/4152690 [==============================] - 1

In [19]:
def predict(i, model):
    
    x_test = np.load('./data_for_prediction/ForecastDataforTesting_201712_' + str(i) + '.npy')
    x_index = np.load('./data_for_prediction/ForecastDataforTesting_Index_201712_'+ str(i) + '.npy')
    df_ref = pd.read_csv('./data_for_prediction/ForecastDataforTesting_Ref_201712_'+ str(i) + '.csv')
    
    x_prediction = model.predict(x_test)
    
    df_ref = pd.merge(df_ref, pd.DataFrame({'ref': x_index, 'wind': x_prediction.flatten()}), how='left', on = 'ref')
    df_ref['wind'] = np.where(df_ref['wind'] >= 0.5, 15, 0)
    del df_ref['ref']
    
    df_ref.sort_values(by=['xid', 'yid', 'date_id', 'hour'], inplace=True)
    
    if os.path.isfile('./data_for_prediction/In_situMeasurementforTesting_201712_'+ str(i) + '.csv'):
        os.remove('./data_for_prediction/In_situMeasurementforTesting_201712_'+ str(i) + '.csv')
        
    df_ref.to_csv('./data_for_prediction/In_situMeasurementforTesting_201712_'+ str(i) + '.csv',header=True, index=False)
    
    
    

In [60]:
i = 6

In [61]:
x_test = np.load('./data_for_prediction/ForecastDataforTesting_201712_' + str(i) + '.npy')
x_index = np.load('./data_for_prediction/ForecastDataforTesting_Index_201712_'+ str(i) + '.npy')
df_ref = pd.read_csv('./data_for_prediction/ForecastDataforTesting_Ref_201712_'+ str(i) + '.csv')

In [64]:
x_prediction = model.predict(x_test)

In [66]:
df_ref = pd.merge(df_ref, pd.DataFrame({'ref': x_index, 'wind': x_prediction.flatten()}), how='left', on = 'ref')
del df_ref['ref']

In [67]:
df_ref['wind'] = np.where(df_ref['wind'] >= 0.5, 15, 0)

In [68]:
pd.DataFrame(x_test.mean(axis=1)).describe()

0
count  4.152744e+06
mean   1.477984e+01
std    3.228680e+00
min    8.120000e-01
25%    1.276000e+01
50%    1.452000e+01
75%    1.664000e+01
max    2.904000e+01

In [69]:

pd.DataFrame(x_prediction.flatten()).describe()

0
count  4.152744e+06
mean   4.171931e-01
std    3.657566e-01
min    2.632085e-03
25%    5.620656e-02
50%    3.041610e-01
75%    8.241350e-01
max    9.694299e-01

In [34]:
np.where(pd.Series([1, 2, 3, 4, 5]) >= 3, 1, 0)

array([0, 0, 1, 1, 1])

In [37]:
df_ref['wind']

array([0])